#include "../../include/debug.h"
#include "../../include/pokemon.h"
#include "../../include/save.h"
#include "../../include/script.h"
#include "../../include/types.h"
#include "../../include/constants/item.h"

#ifdef MART_EXPANSION

struct MartItem {
    u16 item_id;
    u16 override_cost;
};

struct BadgeMartItems {
    u16 item_id;
    u8 required_badges;
};

// note: limited to 203 items (~34 pages)
const struct BadgeMartItems sBadgeMart[] = {
    { ITEM_TM017,           0  },
    { ITEM_ABILITY_CAPSULE, 7  },
    { ITEM_RARE_CANDY,      8  },
    { ITEM_POKE_BALL,       0  },
    { ITEM_GREAT_BALL,      3  },
    { ITEM_ULTRA_BALL,      5  },
    { ITEM_MASTER_BALL,     13 },
    { ITEM_POTION,          0  },
    { ITEM_SUPER_POTION,    1  },
    { ITEM_MAX_POTION,      3  },
    { ITEM_FULL_RESTORE,    5  },
    { ITEM_REVIVE,          2  },
    { ITEM_MAX_REVIVE,      10 },
    { ITEM_FULL_HEAL,       0  },
    { ITEM_LUM_BERRY,       3  },
    { ITEM_ORAN_BERRY,      2  },
    { ITEM_SITRUS_BERRY,    4  },
    { ITEM_AWAKENING,       1  },
    { ITEM_BURN_HEAL,       1  },
    { ITEM_ETHER,           3  },
    { ITEM_ELIXIR,          7  },
    { ITEM_ESCAPE_ROPE,     1  },
    { ITEM_REPEL,           1  },
    { ITEM_SUPER_REPEL,     3  },
    { ITEM_MAX_REPEL,       5  },
}; 

void LONG_CALL InitMartUI(void *taskManager, FieldSystem *fieldSystem, const u16 *items, int kind, int buySell, int decoWhich, const struct MartItem *priceOverrides);

u16 sCherrygroveCityMart[] = {
    ITEM_HEAL_BALL, ITEM_SERIOUS_MINT, ITEM_LAX_MINT, ITEM_RELAXED_MINT, ITEM_BRAVE_MINT, 0xFFFF
};

u16 sVioletCityMart[] = {
    ITEM_NET_BALL, ITEM_NAUGHTY_MINT, ITEM_MILD_MINT, ITEM_LONELY_MINT, ITEM_RASH_MINT,
    ITEM_TM096, ITEM_TM131, ITEM_TM134, ITEM_TM135, 0xFFFF
};

u16 sAzaleaCityMart[] = {
    ITEM_QUICK_BALL, ITEM_GENTLE_MINT, ITEM_CAREFUL_MINT, ITEM_SASSY_MINT, ITEM_HASTY_MINT, ITEM_NAIVE_MINT, 0xFFFF
};

u16 sGoldenrodDepartmentUpper2F[] = {
    ITEM_LONELY_MINT,
    ITEM_ADAMANT_MINT,
    ITEM_NAUGHTY_MINT,
    ITEM_BRAVE_MINT,  
    ITEM_BOLD_MINT,   
    ITEM_IMPISH_MINT, 
    ITEM_LAX_MINT,    
    ITEM_RELAXED_MINT,
    ITEM_MODEST_MINT, 
    ITEM_MILD_MINT,   
    ITEM_RASH_MINT,   
    ITEM_QUIET_MINT,  
    ITEM_CALM_MINT,   
    ITEM_GENTLE_MINT, 
    ITEM_CAREFUL_MINT,
    ITEM_SASSY_MINT,  
    ITEM_TIMID_MINT,  
    ITEM_HASTY_MINT,  
    ITEM_JOLLY_MINT,  
    ITEM_NAIVE_MINT,  
    ITEM_SERIOUS_MINT,
    0xFFFF
};

u16 sGoldenrodDepartmentLower2F[] = {
    ITEM_TR00, ITEM_TR02, ITEM_TR04, ITEM_TR06, ITEM_TR07, ITEM_TR08, ITEM_TR09, 0xFFFF
};

u16 sGoldenrodDepartment3F[] = {
    ITEM_EXP_SHARE, ITEM_FLAME_ORB, ITEM_TOXIC_ORB, ITEM_BLACK_SLUDGE, ITEM_AIR_BALLOON, ITEM_LIGHT_CLAY, ITEM_EJECT_BUTTON, 0xFFFF
};

u16 sGoldenrodDepartment4F[] = {
    ITEM_TR19, ITEM_TR23, ITEM_TR26, ITEM_TR27, ITEM_TR36, ITEM_TR37, ITEM_TR43, 0xFFFF
};

u16 sGoldenrodDepartment5F[] = {
    ITEM_TM00, ITEM_TM070, ITEM_TM017, ITEM_TM054, ITEM_TM083, 
    ITEM_TM033, ITEM_TM022, ITEM_TM052, ITEM_TM038, ITEM_TM025,
    ITEM_TM014, ITEM_TM015, ITEM_TM094, ITEM_TM099, ITEM_TM099, 
    ITEM_TM099, ITEM_TM016, ITEM_TM106, ITEM_TM119, ITEM_TM136,
    ITEM_TM142, ITEM_TM151, ITEM_TM154, ITEM_TM156, 0xFFFF
};

u16 sGoldenrodHerbs[] = {
    ITEM_POWER_HERB, ITEM_HEAL_POWDER, ITEM_ENERGY_POWDER, ITEM_ENERGY_ROOT, ITEM_REVIVAL_HERB, 0xFFFF
};

u16 sEcruteakMart[] = {
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_MOON_STONE,
    ITEM_SUN_STONE,
    ITEM_SHINY_STONE,
    ITEM_DUSK_STONE,
    ITEM_DAWN_STONE,
    ITEM_ICE_STONE,
    ITEM_KINGS_ROCK,
    ITEM_PROTECTOR,
    ITEM_METAL_COAT,
    ITEM_UP_GRADE,
    ITEM_DUBIOUS_DISC,
    ITEM_SYRUPY_APPLE,
    ITEM_TART_APPLE,
    ITEM_SWEET_APPLE,
    ITEM_POWER_BELT,
    ITEM_POWER_ANKLET,
    ITEM_POWER_BAND,
    ITEM_LINKING_CORD,
    0xFFFF
};

u16 sOlivineMart[] = {
    ITEM_NET_BALL, ITEM_LUCKY_EGG, ITEM_TM114, ITEM_TM118, ITEM_TM117, ITEM_TM110, 0xFFFF
};

u16 sCianwoodPharmacy[] = {
    ITEM_TERRAIN_EXTENDER, ITEM_HEAT_ROCK, ITEM_ICY_ROCK, ITEM_DAMP_ROCK, ITEM_SMOOTH_ROCK, 0xFFFF
};

u16 sBlackthornAndBattleFrontierMart[] = {
    ITEM_TR12, ITEM_TR13, ITEM_TR14, ITEM_TR18, ITEM_TR31, ITEM_TR34, ITEM_TR41, 0xFFFF
};

u16 sIndigoPlateau[] = {
    ITEM_CHARIZARDITE_X, ITEM_CHARIZARDITE_Y, ITEM_NET_BALL, ITEM_DUSK_BALL, 
    ITEM_TR12, ITEM_TR13, ITEM_TR14, ITEM_TR18, ITEM_TR31, ITEM_TR34, ITEM_TR41,
    ITEM_REVIVE, ITEM_EXPERT_BELT, ITEM_LIFE_ORB, ITEM_FOCUS_SASH, ITEM_LEFTOVERS,
    ITEM_ROCKY_HELMET, ITEM_ULTRA_BALL, ITEM_MAX_REPEL, ITEM_FULL_RESTORE, 
    0xFFFF
};

u16 sVermilionAndSafariMart[] = {
    ITEM_DUSK_BALL, ITEM_TM157, ITEM_TM122, ITEM_TM123, ITEM_TM124, ITEM_TM125, 0xFFFF
};

u16 sSaffronMart[] = {
    ITEM_TM097, ITEM_TM109, ITEM_TR40, ITEM_TM153, ITEM_TR50, ITEM_AIR_MAIL, ITEM_DUSK_BALL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sLavenderMart[] = {
    ITEM_TM127, ITEM_TR20, ITEM_TR32, ITEM_AIR_MAIL, ITEM_DUSK_BALL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sCeruleanMart[] = {
    ITEM_TR35, ITEM_AIR_MAIL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sCeladonDepartmentUpper2F[] = {
    ITEM_TR00, ITEM_TR01, ITEM_TR02, ITEM_TR03, ITEM_TR04,
    ITEM_TR05, ITEM_TR06, ITEM_TR07, ITEM_TR08, ITEM_TR09,
    ITEM_TR10, ITEM_TR11, ITEM_TR12, ITEM_TR13, ITEM_TR14,
    ITEM_TR15, ITEM_TR16, ITEM_TR17, ITEM_TR18, ITEM_TR19,
    ITEM_TR20, ITEM_TR21, ITEM_TR22, ITEM_TR23, ITEM_TR24,
    ITEM_TR25, ITEM_TR26, ITEM_TR27, ITEM_TR28, ITEM_TR29,
    ITEM_TR30, ITEM_TR31, ITEM_TR32, ITEM_TR33, ITEM_TR34,
    ITEM_TR35, ITEM_TR36, ITEM_TR37, ITEM_TR38, ITEM_TR39,
    ITEM_TR40, ITEM_TR41, ITEM_TR42, ITEM_TR43, ITEM_TR44,
    ITEM_TR45, ITEM_TR46, ITEM_TR47, ITEM_TR48, ITEM_TR49,
    ITEM_TR50, 0xFFFF
};

u16 sCeladonDepartmentLower2F[] = {
    ITEM_CHOICE_BAND, ITEM_CHOICE_SCARF, ITEM_CHOICE_SPECS, 0xFFFF
};

u16 sCeladonDepartment3F[] = {
    ITEM_TM021, ITEM_TM027, ITEM_TM087, ITEM_TM078, ITEM_TM012,
    ITEM_TM041, ITEM_TM020, ITEM_TM028, ITEM_TM076, ITEM_TM055,
    ITEM_TM072, ITEM_TM079, ITEM_TM093, ITEM_TM095, ITEM_TM096, 
    ITEM_TM097, ITEM_TM098, ITEM_TM100, ITEM_TM101, ITEM_TM102, 
    ITEM_TM103, ITEM_TM104, ITEM_TM105, ITEM_TM107, ITEM_TM108, 
    ITEM_TM109, ITEM_TM110, ITEM_TM111, ITEM_TM112, ITEM_TM113, 
    ITEM_TM114, ITEM_TM115, ITEM_TM116, ITEM_TM117, ITEM_TM118, 
    ITEM_TM120, ITEM_TM121, ITEM_TM122, ITEM_TM123, ITEM_TM124, 
    ITEM_TM125, ITEM_TM126, ITEM_TM127, ITEM_TM128, ITEM_TM129, 
    ITEM_TM130, ITEM_TM131, ITEM_TM132, ITEM_TM133, ITEM_TM134, 
    ITEM_TM135, ITEM_TM137, ITEM_TM138, ITEM_TM139, ITEM_TM140, 
    ITEM_TM141, ITEM_TM143, ITEM_TM144, ITEM_TM145, ITEM_TM146, 
    ITEM_TM147, ITEM_TM148, ITEM_TM149, ITEM_TM150, ITEM_TM152, 
    ITEM_TM153, ITEM_TM155, ITEM_TM157, 0xFFFF
};

u16 sCeladonDepartment4F[] = {
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_MOON_STONE,
    ITEM_SUN_STONE,
    ITEM_SHINY_STONE,
    ITEM_DUSK_STONE,
    ITEM_DAWN_STONE,
    ITEM_ICE_STONE,
    ITEM_KINGS_ROCK,
    ITEM_PROTECTOR,
    ITEM_METAL_COAT,
    ITEM_UP_GRADE,
    ITEM_DUBIOUS_DISC,
    ITEM_SYRUPY_APPLE,
    ITEM_TART_APPLE,
    ITEM_SWEET_APPLE,
    ITEM_POWER_BELT,
    ITEM_POWER_ANKLET,
    ITEM_POWER_BAND,
    ITEM_LINKING_CORD,
    0xFFFF
};

u16 sCeladonDepartmentLeft5F[] = {
    ITEM_CHERI_BERRY,
    ITEM_CHESTO_BERRY,
    ITEM_PECHA_BERRY,
    ITEM_RAWST_BERRY, 
    ITEM_ASPEAR_BERRY,
    ITEM_LEPPA_BERRY, 
    ITEM_ORAN_BERRY,  
    ITEM_PERSIM_BERRY,
    ITEM_LUM_BERRY,   
    ITEM_SITRUS_BERRY,
    ITEM_FIGY_BERRY,  
    ITEM_WIKI_BERRY,  
    ITEM_MAGO_BERRY,  
    ITEM_AGUAV_BERRY, 
    ITEM_IAPAPA_BERRY,
    ITEM_RAZZ_BERRY,  
    ITEM_BLUK_BERRY,  
    ITEM_NANAB_BERRY, 
    ITEM_WEPEAR_BERRY,
    ITEM_PINAP_BERRY, 
    ITEM_POMEG_BERRY, 
    ITEM_KELPSY_BERRY,
    ITEM_QUALOT_BERRY,
    ITEM_HONDEW_BERRY,
    ITEM_GREPA_BERRY, 
    ITEM_TAMATO_BERRY,
    ITEM_CORNN_BERRY, 
    ITEM_MAGOST_BERRY,
    ITEM_RABUTA_BERRY,
    ITEM_NOMEL_BERRY, 
    ITEM_SPELON_BERRY,
    ITEM_PAMTRE_BERRY,
    ITEM_WATMEL_BERRY,
    ITEM_DURIN_BERRY,
    ITEM_BELUE_BERRY, 
    ITEM_OCCA_BERRY,  
    ITEM_PASSHO_BERRY,
    ITEM_WACAN_BERRY, 
    ITEM_RINDO_BERRY, 
    ITEM_YACHE_BERRY, 
    ITEM_CHOPLE_BERRY,
    ITEM_KEBIA_BERRY, 
    ITEM_SHUCA_BERRY, 
    ITEM_COBA_BERRY,  
    ITEM_PAYAPA_BERRY,
    ITEM_TANGA_BERRY, 
    ITEM_CHARTI_BERRY,
    ITEM_KASIB_BERRY, 
    ITEM_HABAN_BERRY, 
    ITEM_COLBUR_BERRY,
    ITEM_BABIRI_BERRY,
    ITEM_CHILAN_BERRY,
    ITEM_LIECHI_BERRY,
    ITEM_GANLON_BERRY,
    ITEM_SALAC_BERRY, 
    ITEM_PETAYA_BERRY,
    ITEM_APICOT_BERRY,
    ITEM_LANSAT_BERRY,
    ITEM_STARF_BERRY, 
    ITEM_ENIGMA_BERRY,
    ITEM_MICLE_BERRY, 
    ITEM_CUSTAP_BERRY,
    ITEM_JABOCA_BERRY,
    ITEM_ROWAP_BERRY,
    0xFFFF
};

u16 sCeladonDepartmentRight5F[] = {
    ITEM_PROTEIN, ITEM_IRON, ITEM_CALCIUM, ITEM_ZINC, ITEM_CARBOS,
    ITEM_HP_UP, ITEM_PP_MAX, 0xFFFF
};

u16 sFuschiaMart[] = {
    ITEM_TM155, ITEM_TM095, ITEM_TM139, ITEM_TM143, ITEM_TR29, ITEM_TR38, ITEM_STEEL_MAIL, ITEM_DUSK_BALL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sPewterMart[] = {
    ITEM_TM137, ITEM_TM107, ITEM_TR11, ITEM_TR30, ITEM_TR25, ITEM_STEEL_MAIL, ITEM_NEST_BALL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sViridianMart[] = {
    ITEM_TR39, ITEM_TM100, ITEM_TM112, ITEM_TM128, ITEM_TM129, ITEM_TM130, 
    ITEM_TM132, ITEM_TM133, ITEM_TM147, ITEM_TM148, ITEM_TR01, ITEM_TR03, 
    ITEM_TR05, ITEM_TR10, ITEM_TR21, ITEM_TR22, ITEM_TR24, ITEM_TR42, 
    ITEM_TR44, ITEM_TR45, ITEM_TR46, ITEM_TR47, ITEM_TR48, ITEM_TR49, 
    ITEM_TR28, 0xFFFF
};

u16 sMtMoonSquare[] = {
    ITEM_POKE_DOLL, ITEM_FRESH_WATER, ITEM_SODA_POP, ITEM_LEMONADE, ITEM_REPEL,
    ITEM_HEART_MAIL, 0xFFFF
};

u16 sMahoganyPreRocketHideout[] = {
    ITEM_ULTRA_BALL, ITEM_FULL_RESTORE, ITEM_TM103, ITEM_TM145, ITEM_TM138, 0xFFFF
};

u16 sMahoganyPostRocketHideout[] = {
    ITEM_ULTRA_BALL, ITEM_FULL_RESTORE, ITEM_TM103, ITEM_TM145, ITEM_TM138, 
    ITEM_TM098, ITEM_TM101, ITEM_TM105, ITEM_TM115, ITEM_TM144, ITEM_TM007,
    0xFFFF
};

BOOL ScrCmd_MartBuy(SCRIPTCONTEXT *ctx) {
    u16 unused = ScriptGetVar(ctx);
    
    u16 items[NELEMS(sBadgeMart) + 1];
    u8 badgeCount = 0;
    u8 index = 0;

    for (int i = 0; i < 16; i++) {
        if (PlayerProfile_TestBadgeFlag(Sav2_PlayerData_GetProfileAddr(ctx->fsys->savedata), i) == TRUE) {
            badgeCount++;
        }
    }

    for (int i = 0; i < NELEMS(sBadgeMart); i++) {
        if (badgeCount >= sBadgeMart[i].required_badges) {
            items[index] = sBadgeMart[i].item_id;
            index++;
        }
    }

    items[index] = 0xFFFF;
    InitMartUI(ctx->taskman, ctx->fsys, items, 0, 0, 0, 0); // this doesn't honor price overrides
    return TRUE;
}

#endif // MART_EXPANSION

#ifdef POKEATHLON_SHOP_EXPANSION

const struct MartItem sPokeathlonShopSunday[] = {
    { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_KINGS_ROCK,     3000 },
    { ITEM_HEART_SCALE,    1000 },
    { ITEM_FULL_RESTORE,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_SUN_STONE,      3000 },
    { ITEM_FIRE_STONE,     2500 },
    { ITEM_SHINY_STONE,    3000 },
    { ITEM_DAWN_STONE,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopMonday[] = {
    { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_GREEN_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_MOON_STONE,     3000 },
    { ITEM_RARE_CANDY,     2000 },
    { ITEM_FULL_RESTORE,   500  },
    { ITEM_KINGS_ROCK,     3000 },
    { ITEM_SUN_STONE,      3000 },
    { ITEM_WATER_STONE,    2500 },
    { ITEM_SHINY_STONE,    3000 },
    { ITEM_DUSK_STONE,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopTuesday[] = {
    { ITEM_YELLOW_APRICORN, 200  },
    { ITEM_PINK_APRICORN,   200  },
    { ITEM_WHITE_APRICORN,  200  },
    { ITEM_MOOMOO_MILK,     100  },
    { ITEM_FIRE_STONE,      2500 },
    { ITEM_PP_UP,           1000 },
    { ITEM_FULL_RESTORE,    500  },
    { ITEM_METAL_COAT,      2500 },
    { ITEM_WATER_STONE,     2500 },
    { ITEM_LEAF_STONE,      2500 },
    { ITEM_DUSK_STONE,      3000 },
    { ITEM_DAWN_STONE,      3000 },
    { 0xFFFF,               0    },
};

const struct MartItem sPokeathlonShopWednesday[] = {
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_PINK_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_WATER_STONE,    2500 },
    { ITEM_HEART_SCALE,    1000 },
    { ITEM_FULL_RESTORE,   500  },
    { ITEM_DRAGON_SCALE,   2500 },
    { ITEM_THUNDER_STONE,  2500 },
    { ITEM_MOON_STONE,     3000 },
    { ITEM_SHINY_STONE,    3000 },
    { ITEM_DAWN_STONE,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopThursday[] = {
    { ITEM_YELLOW_APRICORN, 200  },
    { ITEM_PINK_APRICORN,   200  },
    { ITEM_WHITE_APRICORN,  200  },
    { ITEM_MOOMOO_MILK,     100  },
    { ITEM_THUNDER_STONE,   2500 },
    { ITEM_PP_UP,           1000 },
    { ITEM_FULL_RESTORE,    500  },
    { ITEM_KINGS_ROCK,      3000 },
    { ITEM_FIRE_STONE,      2500 },
    { ITEM_LEAF_STONE,      2500 },
    { ITEM_SHINY_STONE,     3000 },
    { ITEM_DUSK_STONE,      3000 },
    { 0xFFFF,               0    },
};

const struct MartItem sPokeathlonShopFriday[] = {
    { ITEM_RED_APRICORN,    200  },
    { ITEM_YELLOW_APRICORN, 200  },
    { ITEM_GREEN_APRICORN,  200  },
    { ITEM_MOOMOO_MILK,     100  },
    { ITEM_METAL_COAT,      2500 },
    { ITEM_NUGGET,          500  },
    { ITEM_FULL_RESTORE,    500  },
    { ITEM_DRAGON_SCALE,    2500 },
    { ITEM_WATER_STONE,     2500 },
    { ITEM_SUN_STONE,       3000 },
    { ITEM_DUSK_STONE,      3000 },
    { ITEM_DAWN_STONE,      3000 },
    { 0xFFFF,               0    },
};

const struct MartItem sPokeathlonShopSaturday[] = {
    { ITEM_GREEN_APRICORN,  200  },
    { ITEM_WHITE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN,  200  },
    { ITEM_MOOMOO_MILK,     100  },
    { ITEM_LEAF_STONE,      2500 },
    { ITEM_RARE_CANDY,      2000 },
    { ITEM_FULL_RESTORE,    500  },
    { ITEM_METAL_COAT,      2500 },
    { ITEM_THUNDER_STONE,   2500 },
    { ITEM_SHINY_STONE,     3000 },
    { ITEM_DUSK_STONE,      3000 },
    { ITEM_DAWN_STONE,      3000 },
    { 0xFFFF,               0    },
};

#endif // POKEATHLON_SHOP_EXPANSION